### ISSUE TITLE
Site is broken

### ISSUE THREAD

**Issue by PranavGPR** [benxene/7days-50projects#141]
I don't know what happened but the site is down.

![image](https://user-images.githubusercontent.com/51258030/129449202-2e0c21bb-a6d6-4e47-a762-ac8f843c2215.png)

**Comment by krissh-codes** [comment]
Kindly test locally and report.
@PranavGPR

**Comment by krissh-codes** [comment]
### Server Log:
```log
[GET] /api/get-projects
20:27:58:89
2021-08-16T14:57:58.997Z	341abfaa-3644-44e7-8a6b-f9c8b56cdaa1	ERROR	Error: ENOENT: no such file or directory, scandir '/var/task/src/pages'
    at Object.readdirSync (fs.js:955:3)
    at handler (/var/task/.next/server/pages/api/get-projects.js:30:37)
    at Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:101:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Server.handleApiRequest (/var/task/node_modules/next/dist/server/next-server.js:760:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:651:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:205:32)
    at async Server.run (/var/task/node_modules/next/dist/server/next-server.js:825:29)
    at async Server.handleRequest (/var/task/node_modules/next/dist/server/next-server.js:292:20)
    at async Server.<anonymous> (/var/task/___next_launcher.js:32:9) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/var/task/src/pages'
}
2021-08-16T14:57:58.997Z	341abfaa-3644-44e7-8a6b-f9c8b56cdaa1	ERROR	Error: ENOENT: no such file or directory, scandir '/var/task/src/pages'
    at Object.readdirSync (fs.js:955:3)
    at handler (/var/task/.next/server/pages/api/get-projects.js:30:37)
    at Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:101:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Server.handleApiRequest (/var/task/node_modules/next/dist/server/next-server.js:760:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:651:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:205:32)
    at async Server.run (/var/task/node_modules/next/dist/server/next-server.js:825:29)
    at async Server.handleRequest (/var/task/node_modules/next/dist/server/next-server.js:292:20)
    at async Server.<anonymous> (/var/task/___next_launcher.js:32:9) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/var/task/src/pages'
}
RequestId: 341abfaa-3644-44e7-8a6b-f9c8b56cdaa1 Error: Runtime exited with error: exit status 1
Runtime.ExitError
[GET] /
20:27:58:25
ni1AdIRggmxSvfedN62Zw.woff2) format('woff2');unicode-range:U+0100-024F,U+0259,U+1E00-1EFF,U+2020,U+20A0-20AB,U+20AD-20CF,U+2113,U+2C60-2C7F,U+A720-A7FF}@font-face{font-family:'Manrope';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/manrope/v4/xn7gYHE41ni1AdIRggexSvfedN4.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:'Manrope';font-style:normal;font-weight:500;font-display:swap;src:url(https://fonts.gstatic.com/s/manrope/v4/xn7gYHE41ni1AdIRggOxSvfedN62Zw.woff2) format('woff2');unicode-range:U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116}@font-face{font-family:'Manrope';font-style:normal;font-weight:500;font-display:swap;src:url(https://fonts.gstatic.com/s/manrope/v4/xn7gYHE41ni1AdIRggSxSvfedN62Zw.woff2) format('woff2');unicode-range:U+0370-03FF}@font-face{font-family:'Manrope';font-style:normal;font-weight:500;font-display:swap;src:url(https://fonts.gstatic.com/s/manrope/v4/xn7gYHE41ni1AdIRggmxSvfedN62Zw.woff2) format('woff2');unicode-range:U+0100-024F,U+0259,U+1E00-1EFF,U+2020,U+20A0-20AB,U+20AD-20CF,U+2113,U+2C60-2C7F,U+A720-A7FF}@font-face{font-family:'Manrope';font-style:normal;font-weight:500;font-display:swap;src:url(https://fonts.gstatic.com/s/manrope/v4/xn7gYHE41ni1AdIRggexSvfedN4.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:'Manrope';font-style:normal;font-weight:800;font-display:swap;src:url(https://fonts.gstatic.com/s/manrope/v4/xn7gYHE41ni1AdIRggOxSvfedN62Zw.woff2) format('woff2');unicode-range:U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116}@font-face{font-family:'Manrope';font-style:normal;font-weight:800;font-display:swap;src:url(https://fonts.gstatic.com/s/manrope/v4/xn7gYHE41ni1AdIRggSxSvfedN62Zw.woff2) format('woff2');unicode-range:U+0370-03FF}@font-face{font-family:'Manrope';font-style:normal;font-weight:800;font-display:swap;src:url(https://fonts.gstatic.com/s/manrope/v4/xn7gYHE41ni1AdIRggmxSvfedN62Zw.woff2) format('woff2');unicode-range:U+0100-024F,U+0259,U+1E00-1EFF,U+2020,U+20A0-20AB,U+20AD-20CF,U+2113,U+2C60-2C7F,U+A720-A7FF}@font-face{font-family:'Manrope';font-style:normal;font-weight:800;font-display:swap;src:url(https://fonts.gstatic.com/s/manrope/v4/xn7gYHE41ni1AdIRggexSvfedN4.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}</style></head><body><div id="__next"><div style="color:#000;background:#fff;font-family:-apple-system, BlinkMacSystemFont, Roboto, &quot;Segoe UI&quot;, &quot;Fira Sans&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;Lucida Grande&quot;, sans-serif;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center"><div><style>body { margin: 0 }</style><h1 style="display:inline-block;border-right:1px solid rgba(0, 0, 0,.3);margin:0;margin-right:20px;padding:10px 23px 10px 0;font-size:24px;font-weight:500;vertical-align:top">500</h1><div style="display:inline-block;text-align:left;line-height:49px;height:49px;vertical-align:middle"><h2 style="font-size:14px;font-weight:normal;line-height:inherit;margin:0;padding:0">Internal Server Error<!-- -->.</h2></div></div></div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":500}},"page":"/_error","query":{},"buildId":"b9R2ue4-jJI-cY1Lk3ZgB","nextExport":true,"isFallback":false,"gip":true,"scriptLoader":[]}</script></body></html>`
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
RequestId: b3e5af8a-9255-4db1-8caf-d821652851d1 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by krissh-codes** [comment]
This problem will probably not be reproducible in dev environment. Try building and serving locally.

**Comment by PranavGPR** [comment]
> This problem will probably not be reproducible in dev environment. Try building and serving locally.

<strong>Local Server log: </strong>

```log
Error: Request failed with status code 500
    at createError (D:\Projects\7days-50projects\.next\serverless\chunks\9669.js:889:15)
    at settle (D:\Projects\7days-50projects\.next\serverless\chunks\9669.js:1148:12)
    at IncomingMessage.handleStreamEnd (D:\Projects\7days-50projects\.next\serverless\chunks\9669.js:275:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    url: '/api/get-projects',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.1'
    },
    baseURL: 'https://7days50projects.vercel.app',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: '7days50projects.vercel.app',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: '7days50projects.vercel.app',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 72,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET /api/get-projects HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/0.21.1\r\n' +
      'Host: 7days50projects.vercel.app\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/api/get-projects',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 500,
      statusMessage: 'Internal Server Error',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://7days50projects.vercel.app/api/get-projects',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: '7days50projects.vercel.app',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://7days50projects.vercel.app/api/get-projects',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 500,
    statusText: 'Internal Server Error',
    headers: {
      date: 'Mon, 16 Aug 2021 15:23:47 GMT',
      'content-type': 'text/html; charset=utf-8',
      connection: 'close',
      'x-matched-path': '/500',
      'content-disposition': 'inline; filename="500"',
      'cache-control': 'public, max-age=0, must-revalidate',
      'content-length': '6265',
      'access-control-allow-origin': '*',
      etag: 'W/"19ddfb6c98d1a58e5ede62fbb6a10cb9afbc312e9d23f359119735d4a247d05f"',
      'accept-ranges': 'bytes',
      'x-vercel-cache': 'HIT',
      age: '1644',
      server: 'Vercel',
      'x-vercel-id': 'bom1::vnxrb-1629127424667-9cff26f75f63',
      'strict-transport-security': 'max-age=63072000; includeSubDomains; preload'
    },
    config: {
      url: '/api/get-projects',
      method: 'get',
      headers: [Object],
      baseURL: 'https://7days50projects.vercel.app',
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /api/get-projects HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: 7days50projects.vercel.app\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/get-projects',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '7days50projects.vercel.app',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: `<!DOCTYPE html><html><head><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /><meta name="v
iewport" content="width=device-width"/><meta charSet="utf-8"/><link rel="icon" href="favicon.png" sizes="16x16 28x28 32x3
2" type="image/png"/><link rel="preconnect" href="https://fonts.gstatic.com"/><link rel="stylesheet" data-href="https://f
onts.googleapis.com/css2?family=Manrope:wght@400;500;800&amp;display=swap" data-optimized-fonts="true"/><title>500: Inter
nal Server Error</title><meta name="next-head-count" content="6"/><noscript data-n-css=""></noscript><script defer="" nom
odule="" src="/_next/static/chunks/polyfills-381dbb3c33243b4920e6.js"></script><script src="/_next/static/chunks/webpack-
2af6b6b3aa2648bb01aa.js" defer=""></script><script src="/_next/static/chunks/framework-ab9173121bc048aad8e7.js" defer="">
</script><script src="/_next/static/chunks/main-cd08cb84179dd68d1456.js" defer=""></script><script src="/_next/static/chu
nks/pages/_app-de9e4939bca11650909e.js" defer=""></script><script src="/_next/static/chunks/pages/_error-03b271b409748e0f
7dc7.js" defer=""></script><script src="/_next/static/b9R2ue4-jJI-cY1Lk3ZgB/_buildManifest.js" defer=""></script><script
src="/_next/static/b9R2ue4-jJI-cY1Lk3ZgB/_ssgManifest.js" defer=""></script><style data-href="https://fonts.googleapis.co
m/css2?family=Manrope:wght@400;500;800&display=swap">@font-face{font-family:'Manrope';font-style:normal;font-weight:400;f
ont-display:swap;src:url(https://fonts.gstatic.com/s/manrope/v4/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk79FO_G.woff) format('woff')
}@font-face{font-family:'Manrope';font-style:normal;font-weight:500;font-display:swap;src:url(https://fonts.gstatic.com/s
/manrope/v4/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk7PFO_G.woff) format('woff')}@font-face{font-family:'Manrope';font-style:normal;
font-weight:800;font-display:swap;src:url(https://fonts.gstatic.com/s/manrope/v4/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk59E-_G.wof
f) format('woff')}@font-face{font-family:'Manrope';font-style:normal;font-weight:400;font-display:swap;src:url(https://fo
nts.gstatic.com/s/manrope/v4/xn7gYHE41ni1AdIRggOxSvfedN62Zw.woff2) format('woff2');unicode-range:U+0400-045F,U+0490-0491,
U+04B0-04B1,U+2116}@font-face{font-family:'Manrope';font-style:normal;font-weight:400;font-display:swap;src:url(https://f
onts.gstatic.com/s/manrope/v4/xn7gYHE41ni1AdIRggSxSvfedN62Zw.woff2) format('woff2');unicode-range:U+0370-03FF}@font-face{
font-family:'Manrope';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/manrope/v4/
xn7gYHE41ni1AdIRggmxSvfedN62Zw.woff2) format('woff2');unicode-range:U+0100-024F,U+0259,U+1E00-1EFF,U+2020,U+20A0-20AB,U+2
0AD-20CF,U+2113,U+2C60-2C7F,U+A720-A7FF}@font-face{font-family:'Manrope';font-style:normal;font-weight:400;font-display:s
wap;src:url(https://fonts.gstatic.com/s/manrope/v4/xn7gYHE41ni1AdIRggexSvfedN4.woff2) format('woff2');unicode-range:U+000
0-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U
+FEFF,U+FFFD}@font-face{font-family:'Manrope';font-style:normal;font-weight:500;font-display:swap;src:url(https://fonts.g
static.com/s/manrope/v4/xn7gYHE41ni1AdIRggOxSvfedN62Zw.woff2) format('woff2');unicode-range:U+0400-045F,U+0490-0491,U+04B
0-04B1,U+2116}@font-face{font-family:'Manrope';font-style:normal;font-weight:500;font-display:swap;src:url(https://fonts.
gstatic.com/s/manrope/v4/xn7gYHE41ni1AdIRggSxSvfedN62Zw.woff2) format('woff2');unicode-range:U+0370-03FF}@font-face{font-
family:'Manrope';font-style:normal;font-weight:500;font-display:swap;src:url(https://fonts.gstatic.com/s/manrope/v4/xn7gY
HE41ni1AdIRggmxSvfedN62Zw.woff2) format('woff2');unicode-range:U+0100-024F,U+0259,U+1E00-1EFF,U+2020,U+20A0-20AB,U+20AD-2
0CF,U+2113,U+2C60-2C7F,U+A720-A7FF}@font-face{font-family:'Manrope';font-style:normal;font-weight:500;font-display:swap;s
rc:url(https://fonts.gstatic.com/s/manrope/v4/xn7gYHE41ni1AdIRggexSvfedN4.woff2) format('woff2');unicode-range:U+0000-00F
F,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF
,U+FFFD}@font-face{font-family:'Manrope';font-style:normal;font-weight:800;font-display:swap;src:url(https://fonts.gstati
c.com/s/manrope/v4/xn7gYHE41ni1AdIRggOxSvfedN62Zw.woff2) format('woff2');unicode-range:U+0400-045F,U+0490-0491,U+04B0-04B
1,U+2116}@font-face{font-family:'Manrope';font-style:normal;font-weight:800;font-display:swap;src:url(https://fonts.gstat
ic.com/s/manrope/v4/xn7gYHE41ni1AdIRggSxSvfedN62Zw.woff2) format('woff2');unicode-range:U+0370-03FF}@font-face{font-famil
y:'Manrope';font-style:normal;font-weight:800;font-display:swap;src:url(https://fonts.gstatic.com/s/manrope/v4/xn7gYHE41n
i1AdIRggmxSvfedN62Zw.woff2) format('woff2');unicode-range:U+0100-024F,U+0259,U+1E00-1EFF,U+2020,U+20A0-20AB,U+20AD-20CF,U
+2113,U+2C60-2C7F,U+A720-A7FF}@font-face{font-family:'Manrope';font-style:normal;font-weight:800;font-display:swap;src:ur
l(https://fonts.gstatic.com/s/manrope/v4/xn7gYHE41ni1AdIRggexSvfedN4.woff2) format('woff2');unicode-range:U+0000-00FF,U+0
131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FF
FD}</style></head><body><div id="__next"><div style="color:#000;background:#fff;font-family:-apple-system, BlinkMacSystem
Font, Roboto, &quot;Segoe UI&quot;, &quot;Fira Sans&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;Lucida Grande&quot;,
 sans-serif;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center">
<div><style>body { margin: 0 }</style><h1 style="display:inline-block;border-right:1px solid rgba(0, 0, 0,.3);margin:0;ma
rgin-right:20px;padding:10px 23px 10px 0;font-size:24px;font-weight:500;vertical-align:top">500</h1><div style="display:i
nline-block;text-align:left;line-height:49px;height:49px;vertical-align:middle"><h2 style="font-size:14px;font-weight:nor
mal;line-height:inherit;margin:0;padding:0">Internal Server Error<!-- -->.</h2></div></div></div></div><script id="__NEXT
_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":500}},"page":"/_error","query":{},"buildId":"b9R2ue4
-jJI-cY1Lk3ZgB","nextExport":true,"isFallback":false,"gip":true,"scriptLoader":[]}</script></body></html>`
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

```

**Comment by krissh-codes** [comment]
Does DEV work fine?

Also, any useful insights?
(I'm clueless why this happens, one possible reason could be any breaking API change)

I will lock the deployment at the last know stable version until we figure it out.

**Comment by krissh-codes** [comment]
> I will lock the deployment at the last know stable version until we figure it out.

Current deployment is locked at: ccd50dc5f1fb8e7b794abbf65d58b14c644a7487

**Comment by PranavGPR** [comment]
> Does DEV work fine?
> 
> Also, any useful insights?
> (I'm clueless why this happens, one possible reason could be any breaking API change)
> 
> I will lock the deployment at the last know stable version until we figure it out.

DEV environment works fine without any problem.

**Comment by sank2000** [comment]
![Capture](https://user-images.githubusercontent.com/51191409/129743584-215ad322-b19f-46d9-88d6-0aafd6ff0768.PNG)



weird but working fine now

**Comment by sank2000** [comment]
@PranavGPR @KrishnaMoorthy12  check once  again

**Comment by PranavGPR** [comment]
> ![Capture](https://user-images.githubusercontent.com/51191409/129743584-215ad322-b19f-46d9-88d6-0aafd6ff0768.PNG)
> 
> weird but working fine now

That's because @KrishnaMoorthy12 deployed an old commit instead of the latest one.

**Comment by krissh-codes** [comment]
> ![Capture](https://user-images.githubusercontent.com/51191409/129743584-215ad322-b19f-46d9-88d6-0aafd6ff0768.PNG)
> 
> weird but working fine now

I reverted back to the last known stable build.

**Comment by PranavGPR** [comment]
Any updates on this issue??

**Comment by krissh-codes** [comment]
No, I haven't been working much lately. I'm in a perplexed state because of job hunting and stuff.

**Comment by PranavGPR** [comment]
We haven't found anything of this issue till now, right?
